// Generated by scripts/generate-gallery-data.mjs.
window.PORTFOLIO_GALLERIES = {
  "friends": {
    "title": "Friends",
    "description": "Production photography from Kobo Abe's Friends (1967).",
    "items": [
      {
        "src": "img/friends-applause.jpeg",
        "alt": "Friends: applause"
      },
      {
        "src": "img/friends-blood-close.jpeg",
        "alt": "Friends: blood close"
      },
      {
        "src": "img/friends-blood-fence.jpeg",
        "alt": "Friends: blood fence"
      },
      {
        "src": "img/friends-blood-stand.jpeg",
        "alt": "Friends: blood stand"
      },
      {
        "src": "img/friends-cage.jpeg",
        "alt": "Friends: cage"
      },
      {
        "src": "img/friends-curly.jpeg",
        "alt": "Friends: curly"
      },
      {
        "src": "img/friends-embrace.jpeg",
        "alt": "Friends: embrace"
      },
      {
        "src": "img/friends-fence.jpeg",
        "alt": "Friends: fence"
      },
      {
        "src": "img/friends-floor.jpeg",
        "alt": "Friends: floor"
      },
      {
        "src": "img/friends-girl-fence.jpeg",
        "alt": "Friends: girl fence"
      },
      {
        "src": "img/friends-group.jpeg",
        "alt": "Friends: group"
      },
      {
        "src": "img/friends-hero.jpeg",
        "alt": "Friends: hero"
      },
      {
        "src": "img/friends-red-profile.jpeg",
        "alt": "Friends: red profile"
      },
      {
        "src": "img/friends-table.jpeg",
        "alt": "Friends: table"
      },
      {
        "src": "img/friends-wide.jpeg",
        "alt": "Friends: wide"
      }
    ]
  },
  "glass": {
    "title": "Great Glass Elevator",
    "description": "Production photography from Mark Branner's adaptation of Roald Dahl's Charlie and the Great Glass Elevator (2026).",
    "items": [
      {
        "src": "img/glass-01.jpg",
        "alt": "Great Glass Elevator: 01"
      },
      {
        "src": "img/glass-02.jpg",
        "alt": "Great Glass Elevator: 02"
      },
      {
        "src": "img/glass-03.jpg",
        "alt": "Great Glass Elevator: 03"
      },
      {
        "src": "img/glass-04.jpg",
        "alt": "Great Glass Elevator: 04"
      },
      {
        "src": "img/glass-05.jpg",
        "alt": "Great Glass Elevator: 05"
      },
      {
        "src": "img/glass-06.jpg",
        "alt": "Great Glass Elevator: 06"
      },
      {
        "src": "img/glass-07.jpg",
        "alt": "Great Glass Elevator: 07"
      },
      {
        "src": "img/glass-08.jpg",
        "alt": "Great Glass Elevator: 08"
      },
      {
        "src": "img/glass-09.jpg",
        "alt": "Great Glass Elevator: 09"
      },
      {
        "src": "img/glass-10.jpg",
        "alt": "Great Glass Elevator: 10"
      },
      {
        "src": "img/glass-11.jpg",
        "alt": "Great Glass Elevator: 11"
      },
      {
        "src": "img/glass-12.jpg",
        "alt": "Great Glass Elevator: 12"
      },
      {
        "src": "img/glass-13.jpg",
        "alt": "Great Glass Elevator: 13"
      },
      {
        "src": "img/glass-14.jpg",
        "alt": "Great Glass Elevator: 14"
      },
      {
        "src": "img/glass-15.jpg",
        "alt": "Great Glass Elevator: 15"
      },
      {
        "src": "img/glass-16.jpg",
        "alt": "Great Glass Elevator: 16"
      }
    ]
  },
  "france": {
    "title": "France",
    "description": "Travel photographs from France.",
    "items": [
      {
        "src": "img/france-eiffel-night.jpeg",
        "alt": "France: eiffel night"
      },
      {
        "src": "img/france-grand-palais-friends.jpg",
        "alt": "France: grand palais friends"
      },
      {
        "src": "img/france-invalides-cross.jpg",
        "alt": "France: invalides cross"
      },
      {
        "src": "img/france-invalides-crucifix.jpg",
        "alt": "France: invalides crucifix"
      },
      {
        "src": "img/france-invalides-turenne.jpg",
        "alt": "France: invalides turenne"
      },
      {
        "src": "img/france-louvre-bust.jpg",
        "alt": "France: louvre bust"
      },
      {
        "src": "img/france-louvre-cupid.jpeg",
        "alt": "France: louvre cupid"
      },
      {
        "src": "img/france-louvre-gallery.jpeg",
        "alt": "France: louvre gallery"
      },
      {
        "src": "img/france-louvre-monalisa.jpeg",
        "alt": "France: louvre monalisa"
      },
      {
        "src": "img/france-louvre-nike.jpeg",
        "alt": "France: louvre nike"
      },
      {
        "src": "img/france-louvre-old-man.jpeg",
        "alt": "France: louvre old man"
      },
      {
        "src": "img/france-louvre-psyche.jpg",
        "alt": "France: louvre psyche"
      },
      {
        "src": "img/france-louvre-pyramid.jpg",
        "alt": "France: louvre pyramid"
      },
      {
        "src": "img/france-louvre-reclining.jpeg",
        "alt": "France: louvre reclining"
      },
      {
        "src": "img/france-louvre-three-graces.jpg",
        "alt": "France: louvre three graces"
      },
      {
        "src": "img/france-louvre-venus.jpeg",
        "alt": "France: louvre venus"
      },
      {
        "src": "img/france-opera-hall.jpeg",
        "alt": "France: opera hall"
      },
      {
        "src": "img/france-orsay-clock.jpeg",
        "alt": "France: orsay clock"
      },
      {
        "src": "img/france-orsay-silhouette.jpeg",
        "alt": "France: orsay silhouette"
      },
      {
        "src": "img/france-orsay-starry-night.jpg",
        "alt": "France: orsay starry night"
      },
      {
        "src": "img/france-orsay-vangogh-portrait.jpg",
        "alt": "France: orsay vangogh portrait"
      },
      {
        "src": "img/france-paris-hotel-de-ville.jpeg",
        "alt": "France: paris hotel de ville"
      },
      {
        "src": "img/france-sculpture-gladiator.jpeg",
        "alt": "France: sculpture gladiator"
      },
      {
        "src": "img/france-sculpture-grief.jpeg",
        "alt": "France: sculpture grief"
      },
      {
        "src": "img/france-sculpture-nature.jpeg",
        "alt": "France: sculpture nature"
      },
      {
        "src": "img/france-versailles-battles.jpeg",
        "alt": "France: versailles battles"
      },
      {
        "src": "img/france-versailles-chandeliers.jpeg",
        "alt": "France: versailles chandeliers"
      },
      {
        "src": "img/france-versailles-gallery.jpeg",
        "alt": "France: versailles gallery"
      },
      {
        "src": "img/france-versailles-room.jpeg",
        "alt": "France: versailles room"
      }
    ]
  },
  "italy": {
    "title": "Italy",
    "description": "Travel photographs from Italy.",
    "items": [
      {
        "src": "img/italy-area-pedonale.jpg",
        "alt": "Italy: area pedonale"
      },
      {
        "src": "img/italy-birth-of-venus.jpg",
        "alt": "Italy: birth of venus"
      },
      {
        "src": "img/italy-botticelli-primavera.jpg",
        "alt": "Italy: botticelli primavera"
      },
      {
        "src": "img/italy-church-apse-detail.jpg",
        "alt": "Italy: church apse detail"
      },
      {
        "src": "img/italy-church-apse.jpg",
        "alt": "Italy: church apse"
      },
      {
        "src": "img/italy-colosseum-interior.jpg",
        "alt": "Italy: colosseum interior"
      },
      {
        "src": "img/italy-dancing-faun.jpg",
        "alt": "Italy: dancing faun"
      },
      {
        "src": "img/italy-dome-fresco.jpg",
        "alt": "Italy: dome fresco"
      },
      {
        "src": "img/italy-duomo-entrance.jpg",
        "alt": "Italy: duomo entrance"
      },
      {
        "src": "img/italy-gregory-monument.jpg",
        "alt": "Italy: gregory monument"
      },
      {
        "src": "img/italy-loggia-sculpture.jpg",
        "alt": "Italy: loggia sculpture"
      },
      {
        "src": "img/italy-piazza-navona-church.jpg",
        "alt": "Italy: piazza navona church"
      },
      {
        "src": "img/italy-piazza-navona.jpg",
        "alt": "Italy: piazza navona"
      },
      {
        "src": "img/italy-piazzale-sunset.jpg",
        "alt": "Italy: piazzale sunset"
      },
      {
        "src": "img/italy-rome-domes-skyline.jpg",
        "alt": "Italy: rome domes skyline"
      },
      {
        "src": "img/italy-sant-ignazio-ceiling.jpg",
        "alt": "Italy: sant ignazio ceiling"
      },
      {
        "src": "img/italy-trevi-fountain.jpg",
        "alt": "Italy: trevi fountain"
      },
      {
        "src": "img/italy-trevi-neptune.jpg",
        "alt": "Italy: trevi neptune"
      },
      {
        "src": "img/italy-winged-victory-horses.jpg",
        "alt": "Italy: winged victory horses"
      }
    ]
  },
  "uk": {
    "title": "United Kingdom",
    "description": "Travel photographs from the United Kingdom.",
    "items": [
      {
        "src": "img/uk-aberdeen-signpost-glass.jpg",
        "alt": "United Kingdom: aberdeen signpost glass"
      },
      {
        "src": "img/uk-balmoral-calton-hill.jpg",
        "alt": "United Kingdom: balmoral calton hill"
      },
      {
        "src": "img/uk-balmoral-clock-tower.jpg",
        "alt": "United Kingdom: balmoral clock tower"
      },
      {
        "src": "img/uk-balmoral-hotel-daytime.jpg",
        "alt": "United Kingdom: balmoral hotel daytime"
      },
      {
        "src": "img/uk-birch-forest-trunks.jpg",
        "alt": "United Kingdom: birch forest trunks"
      },
      {
        "src": "img/uk-blackpool-tower-sky.jpg",
        "alt": "United Kingdom: blackpool tower sky"
      },
      {
        "src": "img/uk-blackpool-tower-square.jpg",
        "alt": "United Kingdom: blackpool tower square"
      },
      {
        "src": "img/uk-blackpool-typography-floor.jpg",
        "alt": "United Kingdom: blackpool typography floor"
      },
      {
        "src": "img/uk-blue-door-bare-tree.jpg",
        "alt": "United Kingdom: blue door bare tree"
      },
      {
        "src": "img/uk-bonfire-flames.jpg",
        "alt": "United Kingdom: bonfire flames"
      },
      {
        "src": "img/uk-bonfire-music-sand.jpg",
        "alt": "United Kingdom: bonfire music sand"
      },
      {
        "src": "img/uk-bonfire-night-phones.jpg",
        "alt": "United Kingdom: bonfire night phones"
      },
      {
        "src": "img/uk-brick-building-rain.jpg",
        "alt": "United Kingdom: brick building rain"
      },
      {
        "src": "img/uk-calton-hill-dusk.jpg",
        "alt": "United Kingdom: calton hill dusk"
      },
      {
        "src": "img/uk-calton-hill-monument.jpg",
        "alt": "United Kingdom: calton hill monument"
      },
      {
        "src": "img/uk-church-nave-stained-glass.jpg",
        "alt": "United Kingdom: church nave stained glass"
      },
      {
        "src": "img/uk-church-stained-glass-reading.jpg",
        "alt": "United Kingdom: church stained glass reading"
      },
      {
        "src": "img/uk-church-stained-glass-saints.jpg",
        "alt": "United Kingdom: church stained glass saints"
      },
      {
        "src": "img/uk-cottage-blue-car-garden.jpg",
        "alt": "United Kingdom: cottage blue car garden"
      },
      {
        "src": "img/uk-cottage-blue-sky.jpg",
        "alt": "United Kingdom: cottage blue sky"
      },
      {
        "src": "img/uk-countryside-fence-gorse.jpg",
        "alt": "United Kingdom: countryside fence gorse"
      },
      {
        "src": "img/uk-dance-studio-discussion.jpg",
        "alt": "United Kingdom: dance studio discussion"
      },
      {
        "src": "img/uk-edinburgh-castle.jpg",
        "alt": "United Kingdom: edinburgh castle"
      },
      {
        "src": "img/uk-edinburgh-child-umbrella.jpg",
        "alt": "United Kingdom: edinburgh child umbrella"
      },
      {
        "src": "img/uk-edinburgh-graduation-friends.jpg",
        "alt": "United Kingdom: edinburgh graduation friends"
      },
      {
        "src": "img/uk-edinburgh-graduation-solo.jpg",
        "alt": "United Kingdom: edinburgh graduation solo"
      },
      {
        "src": "img/uk-edinburgh-panorama.jpg",
        "alt": "United Kingdom: edinburgh panorama"
      },
      {
        "src": "img/uk-edinburgh-uni-quad-evening.jpg",
        "alt": "United Kingdom: edinburgh uni quad evening"
      },
      {
        "src": "img/uk-edinburgh-university.jpg",
        "alt": "United Kingdom: edinburgh university"
      },
      {
        "src": "img/uk-foggy-town-rooftops.jpg",
        "alt": "United Kingdom: foggy town rooftops"
      },
      {
        "src": "img/uk-forest-canopy-lookup.jpg",
        "alt": "United Kingdom: forest canopy lookup"
      },
      {
        "src": "img/uk-friends-backstage-flowers.jpg",
        "alt": "United Kingdom: friends backstage flowers"
      },
      {
        "src": "img/uk-friends-portrait.jpg",
        "alt": "United Kingdom: friends portrait"
      },
      {
        "src": "img/uk-glasgow-kelvinbridge-sign.jpg",
        "alt": "United Kingdom: glasgow kelvinbridge sign"
      },
      {
        "src": "img/uk-glasgow-uni-gothic.jpg",
        "alt": "United Kingdom: glasgow uni gothic"
      },
      {
        "src": "img/uk-glenfinnan-viaduct-portrait.jpg",
        "alt": "United Kingdom: glenfinnan viaduct portrait"
      },
      {
        "src": "img/uk-gothic-ivy-red-leaves.jpg",
        "alt": "United Kingdom: gothic ivy red leaves"
      },
      {
        "src": "img/uk-gothic-stone-doorway.jpg",
        "alt": "United Kingdom: gothic stone doorway"
      },
      {
        "src": "img/uk-highlands-arm-raised.jpg",
        "alt": "United Kingdom: highlands arm raised"
      },
      {
        "src": "img/uk-highlands-golden-hills.jpg",
        "alt": "United Kingdom: highlands golden hills"
      },
      {
        "src": "img/uk-highlands-loch-view.jpg",
        "alt": "United Kingdom: highlands loch view"
      },
      {
        "src": "img/uk-highlands-village-portrait.jpg",
        "alt": "United Kingdom: highlands village portrait"
      },
      {
        "src": "img/uk-hiker-forest-path.jpg",
        "alt": "United Kingdom: hiker forest path"
      },
      {
        "src": "img/uk-london-big-ben.jpg",
        "alt": "United Kingdom: london big ben"
      },
      {
        "src": "img/uk-london-bridge-sunset.jpg",
        "alt": "United Kingdom: london bridge sunset"
      },
      {
        "src": "img/uk-london-eye-river.jpg",
        "alt": "United Kingdom: london eye river"
      },
      {
        "src": "img/uk-london-street-scene.jpg",
        "alt": "United Kingdom: london street scene"
      },
      {
        "src": "img/uk-night-closeup-flash.jpg",
        "alt": "United Kingdom: night closeup flash"
      },
      {
        "src": "img/uk-night-friends-bottles.jpg",
        "alt": "United Kingdom: night friends bottles"
      },
      {
        "src": "img/uk-night-moon-graffiti.jpg",
        "alt": "United Kingdom: night moon graffiti"
      },
      {
        "src": "img/uk-night-street-varsity-jacket.jpg",
        "alt": "United Kingdom: night street varsity jacket"
      },
      {
        "src": "img/uk-pentland-hills-cafe.jpg",
        "alt": "United Kingdom: pentland hills cafe"
      },
      {
        "src": "img/uk-pine-tree-golden-cones.jpg",
        "alt": "United Kingdom: pine tree golden cones"
      },
      {
        "src": "img/uk-princes-street-silhouette.jpg",
        "alt": "United Kingdom: princes street silhouette"
      },
      {
        "src": "img/uk-pub-interior.jpg",
        "alt": "United Kingdom: pub interior"
      },
      {
        "src": "img/uk-reservoir-bridge-blue.jpg",
        "alt": "United Kingdom: reservoir bridge blue"
      },
      {
        "src": "img/uk-reservoir-warning-sign.jpg",
        "alt": "United Kingdom: reservoir warning sign"
      },
      {
        "src": "img/uk-reservoir-wide-view.jpg",
        "alt": "United Kingdom: reservoir wide view"
      },
      {
        "src": "img/uk-river-birch-trees.jpg",
        "alt": "United Kingdom: river birch trees"
      },
      {
        "src": "img/uk-river-rapids-branches.jpg",
        "alt": "United Kingdom: river rapids branches"
      },
      {
        "src": "img/uk-road-sign-speed.jpg",
        "alt": "United Kingdom: road sign speed"
      },
      {
        "src": "img/uk-seaside-portrait.jpg",
        "alt": "United Kingdom: seaside portrait"
      },
      {
        "src": "img/uk-stage-bow.jpg",
        "alt": "United Kingdom: stage bow"
      },
      {
        "src": "img/uk-tree-branches-silhouette.jpg",
        "alt": "United Kingdom: tree branches silhouette"
      },
      {
        "src": "img/uk-winter-trees-blue-sky.jpg",
        "alt": "United Kingdom: winter trees blue sky"
      }
    ]
  },
  "japan": {
    "title": "Japan",
    "description": "Travel photographs from Japan.",
    "items": [
      {
        "src": "img/japan-art-center-glass.jpg",
        "alt": "Japan: art center glass"
      },
      {
        "src": "img/japan-art-center-interior.jpg",
        "alt": "Japan: art center interior"
      },
      {
        "src": "img/japan-autumn-window-reflection.jpg",
        "alt": "Japan: autumn window reflection"
      },
      {
        "src": "img/japan-bicycle-ginkgo.jpg",
        "alt": "Japan: bicycle ginkgo"
      },
      {
        "src": "img/japan-bus-interior.jpg",
        "alt": "Japan: bus interior"
      },
      {
        "src": "img/japan-cafe-camera-portrait.jpg",
        "alt": "Japan: cafe camera portrait"
      },
      {
        "src": "img/japan-cafe-terrace.jpg",
        "alt": "Japan: cafe terrace"
      },
      {
        "src": "img/japan-crosswalk-shadow.jpg",
        "alt": "Japan: crosswalk shadow"
      },
      {
        "src": "img/japan-fuji-morning-portrait.jpg",
        "alt": "Japan: fuji morning portrait"
      },
      {
        "src": "img/japan-fuji-trees-portrait.jpg",
        "alt": "Japan: fuji trees portrait"
      },
      {
        "src": "img/japan-fuji-village-view.jpg",
        "alt": "Japan: fuji village view"
      },
      {
        "src": "img/japan-garden-lantern.jpg",
        "alt": "Japan: garden lantern"
      },
      {
        "src": "img/japan-ginkgo-leaves-street.jpg",
        "alt": "Japan: ginkgo leaves street"
      },
      {
        "src": "img/japan-hakone-lake-torii.jpg",
        "alt": "Japan: hakone lake torii"
      },
      {
        "src": "img/japan-houtou-fuji-lantern.jpg",
        "alt": "Japan: houtou fuji lantern"
      },
      {
        "src": "img/japan-museum-painting.jpg",
        "alt": "Japan: museum painting"
      },
      {
        "src": "img/japan-nakameguro-crowd.jpg",
        "alt": "Japan: nakameguro crowd"
      },
      {
        "src": "img/japan-nakameguro-street.jpg",
        "alt": "Japan: nakameguro street"
      },
      {
        "src": "img/japan-nankai-train-interior.jpg",
        "alt": "Japan: nankai train interior"
      },
      {
        "src": "img/japan-narukawa-museum-sign.jpg",
        "alt": "Japan: narukawa museum sign"
      },
      {
        "src": "img/japan-noa-dance-cityscape.jpg",
        "alt": "Japan: noa dance cityscape"
      },
      {
        "src": "img/japan-noh-masks-hannya.jpg",
        "alt": "Japan: noh masks hannya"
      },
      {
        "src": "img/japan-noh-masks-women.jpg",
        "alt": "Japan: noh masks women"
      },
      {
        "src": "img/japan-osaka-shinsaibashi-signs.jpg",
        "alt": "Japan: osaka shinsaibashi signs"
      },
      {
        "src": "img/japan-osaka-shinsekai-portrait.jpg",
        "alt": "Japan: osaka shinsekai portrait"
      },
      {
        "src": "img/japan-osaka-tsutenkaku-street.jpg",
        "alt": "Japan: osaka tsutenkaku street"
      },
      {
        "src": "img/japan-osaka-tsutenkaku-tower.jpg",
        "alt": "Japan: osaka tsutenkaku tower"
      },
      {
        "src": "img/japan-owakudani-steam.jpg",
        "alt": "Japan: owakudani steam"
      },
      {
        "src": "img/japan-ryokan-exterior.jpg",
        "alt": "Japan: ryokan exterior"
      },
      {
        "src": "img/japan-ryokan-fuji-window.jpg",
        "alt": "Japan: ryokan fuji window"
      },
      {
        "src": "img/japan-shibuya-night.jpg",
        "alt": "Japan: shibuya night"
      },
      {
        "src": "img/japan-shinjuku-signs.jpg",
        "alt": "Japan: shinjuku signs"
      },
      {
        "src": "img/japan-shrine-torii-ginkgo.jpg",
        "alt": "Japan: shrine torii ginkgo"
      },
      {
        "src": "img/japan-street-vendor.jpg",
        "alt": "Japan: street vendor"
      },
      {
        "src": "img/japan-street-worker.jpg",
        "alt": "Japan: street worker"
      },
      {
        "src": "img/japan-taxi-restaurant.jpg",
        "alt": "Japan: taxi restaurant"
      },
      {
        "src": "img/japan-temple-plaza.jpg",
        "alt": "Japan: temple plaza"
      },
      {
        "src": "img/japan-tokyo-tower-close.jpg",
        "alt": "Japan: tokyo tower close"
      },
      {
        "src": "img/japan-tokyo-tower-detail.jpg",
        "alt": "Japan: tokyo tower detail"
      },
      {
        "src": "img/japan-tokyo-tower-skyline.jpg",
        "alt": "Japan: tokyo tower skyline"
      },
      {
        "src": "img/japan-tokyo-tower-wide.jpg",
        "alt": "Japan: tokyo tower wide"
      },
      {
        "src": "img/japan-tower-reflection-building.jpg",
        "alt": "Japan: tower reflection building"
      },
      {
        "src": "img/japan-village-stream.jpg",
        "alt": "Japan: village stream"
      }
    ]
  },
  "spain": {
    "title": "Spain",
    "description": "Travel photographs from Spain.",
    "items": [
      {
        "src": "img/spain-barcelona-palm-blue.jpg",
        "alt": "Spain: barcelona palm blue"
      },
      {
        "src": "img/spain-barcelona-skyline-sagrada.jpg",
        "alt": "Spain: barcelona skyline sagrada"
      },
      {
        "src": "img/spain-barceloneta-beach-crowd.jpg",
        "alt": "Spain: barceloneta beach crowd"
      },
      {
        "src": "img/spain-batllo-arches.jpg",
        "alt": "Spain: batllo arches"
      },
      {
        "src": "img/spain-batllo-kitchen.jpg",
        "alt": "Spain: batllo kitchen"
      },
      {
        "src": "img/spain-batllo-roof-mosaic.jpg",
        "alt": "Spain: batllo roof mosaic"
      },
      {
        "src": "img/spain-batllo-stained-glass.jpg",
        "alt": "Spain: batllo stained glass"
      },
      {
        "src": "img/spain-beach-dusk-back.jpg",
        "alt": "Spain: beach dusk back"
      },
      {
        "src": "img/spain-beach-dusk-whotel.jpg",
        "alt": "Spain: beach dusk whotel"
      },
      {
        "src": "img/spain-beach-night-portrait.jpg",
        "alt": "Spain: beach night portrait"
      },
      {
        "src": "img/spain-beach-volleyball.jpg",
        "alt": "Spain: beach volleyball"
      },
      {
        "src": "img/spain-canary-coast-palms.jpg",
        "alt": "Spain: canary coast palms"
      },
      {
        "src": "img/spain-canary-ocean-rocks.jpg",
        "alt": "Spain: canary ocean rocks"
      },
      {
        "src": "img/spain-canary-resort-flowers.jpg",
        "alt": "Spain: canary resort flowers"
      },
      {
        "src": "img/spain-canary-resort-flowers2.jpg",
        "alt": "Spain: canary resort flowers2"
      },
      {
        "src": "img/spain-canary-road-signs.jpg",
        "alt": "Spain: canary road signs"
      },
      {
        "src": "img/spain-canary-sunset-clouds.jpg",
        "alt": "Spain: canary sunset clouds"
      },
      {
        "src": "img/spain-canary-sunset-silhouette.jpg",
        "alt": "Spain: canary sunset silhouette"
      },
      {
        "src": "img/spain-gallery-body-screen.jpg",
        "alt": "Spain: gallery body screen"
      },
      {
        "src": "img/spain-gallery-desk-closeup.jpg",
        "alt": "Spain: gallery desk closeup"
      },
      {
        "src": "img/spain-gallery-installation-cube.jpg",
        "alt": "Spain: gallery installation cube"
      },
      {
        "src": "img/spain-gallery-projection.jpg",
        "alt": "Spain: gallery projection"
      },
      {
        "src": "img/spain-gallery-puppets.jpg",
        "alt": "Spain: gallery puppets"
      },
      {
        "src": "img/spain-gallery-tv-bw.jpg",
        "alt": "Spain: gallery tv BW"
      },
      {
        "src": "img/spain-gallery-vitrine.jpg",
        "alt": "Spain: gallery vitrine"
      },
      {
        "src": "img/spain-gallery-wood-lamp.jpg",
        "alt": "Spain: gallery wood lamp"
      },
      {
        "src": "img/spain-hilltop-cityview.jpg",
        "alt": "Spain: hilltop cityview"
      },
      {
        "src": "img/spain-macba-skaters.jpg",
        "alt": "Spain: macba skaters"
      },
      {
        "src": "img/spain-orange-wall-cables.jpg",
        "alt": "Spain: orange wall cables"
      },
      {
        "src": "img/spain-pedrera-balcony.jpg",
        "alt": "Spain: pedrera balcony"
      },
      {
        "src": "img/spain-pedrera-chimney-sky.jpg",
        "alt": "Spain: pedrera chimney sky"
      },
      {
        "src": "img/spain-pedrera-facade-closeup.jpg",
        "alt": "Spain: pedrera facade closeup"
      },
      {
        "src": "img/spain-pedrera-facade-wide.jpg",
        "alt": "Spain: pedrera facade wide"
      },
      {
        "src": "img/spain-sagrada-blue-vault.jpg",
        "alt": "Spain: sagrada blue vault"
      },
      {
        "src": "img/spain-sagrada-golden-light.jpg",
        "alt": "Spain: sagrada golden light"
      },
      {
        "src": "img/spain-sagrada-interior-blue.jpg",
        "alt": "Spain: sagrada interior blue"
      },
      {
        "src": "img/spain-sagrada-stained-glass-warm.jpg",
        "alt": "Spain: sagrada stained glass warm"
      },
      {
        "src": "img/spain-seville-alfonso-flowers.jpg",
        "alt": "Spain: seville alfonso flowers"
      },
      {
        "src": "img/spain-seville-alley.jpg",
        "alt": "Spain: seville alley"
      },
      {
        "src": "img/spain-seville-cathedral.jpg",
        "alt": "Spain: seville cathedral"
      },
      {
        "src": "img/spain-seville-courtyard.jpg",
        "alt": "Spain: seville courtyard"
      },
      {
        "src": "img/spain-seville-palms-building.jpg",
        "alt": "Spain: seville palms building"
      },
      {
        "src": "img/spain-seville-parasol.jpg",
        "alt": "Spain: seville parasol"
      },
      {
        "src": "img/spain-seville-plaza-arcade.jpg",
        "alt": "Spain: seville plaza arcade"
      },
      {
        "src": "img/spain-seville-protest.jpg",
        "alt": "Spain: seville protest"
      },
      {
        "src": "img/spain-seville-street-warm.jpg",
        "alt": "Spain: seville street warm"
      },
      {
        "src": "img/spain-silhouette-green-text.jpg",
        "alt": "Spain: silhouette green text"
      }
    ]
  },
  "iceland": {
    "title": "Iceland",
    "description": "Travel photographs from Iceland.",
    "items": [
      {
        "src": "img/iceland-black-beach-walk.jpg",
        "alt": "Iceland: black beach walk"
      },
      {
        "src": "img/iceland-black-sand-rocks.jpg",
        "alt": "Iceland: black sand rocks"
      },
      {
        "src": "img/iceland-blue-water.jpg",
        "alt": "Iceland: blue water"
      },
      {
        "src": "img/iceland-blur-portrait.jpg",
        "alt": "Iceland: blur portrait"
      },
      {
        "src": "img/iceland-boat-deck.jpg",
        "alt": "Iceland: boat deck"
      },
      {
        "src": "img/iceland-boat-window-sea.jpg",
        "alt": "Iceland: boat window sea"
      },
      {
        "src": "img/iceland-bus-window.jpg",
        "alt": "Iceland: bus window"
      },
      {
        "src": "img/iceland-cliff-arms-ocean.jpg",
        "alt": "Iceland: cliff arms ocean"
      },
      {
        "src": "img/iceland-cliff-silhouette.jpg",
        "alt": "Iceland: cliff silhouette"
      },
      {
        "src": "img/iceland-cliff-sunset.jpg",
        "alt": "Iceland: cliff sunset"
      },
      {
        "src": "img/iceland-diamond-beach.jpg",
        "alt": "Iceland: diamond beach"
      },
      {
        "src": "img/iceland-dusk-reach.jpg",
        "alt": "Iceland: dusk reach"
      },
      {
        "src": "img/iceland-ferry-couple.jpg",
        "alt": "Iceland: ferry couple"
      },
      {
        "src": "img/iceland-flag-boat.jpg",
        "alt": "Iceland: flag boat"
      },
      {
        "src": "img/iceland-glacier-van.jpg",
        "alt": "Iceland: glacier van"
      },
      {
        "src": "img/iceland-gullfoss-aerial.jpg",
        "alt": "Iceland: gullfoss aerial"
      },
      {
        "src": "img/iceland-gullfoss-overlook.jpg",
        "alt": "Iceland: gullfoss overlook"
      },
      {
        "src": "img/iceland-hand-mountains.jpg",
        "alt": "Iceland: hand mountains"
      },
      {
        "src": "img/iceland-harbor-fjord.jpg",
        "alt": "Iceland: harbor fjord"
      },
      {
        "src": "img/iceland-headlamp.jpg",
        "alt": "Iceland: headlamp"
      },
      {
        "src": "img/iceland-horse-group.jpg",
        "alt": "Iceland: horse group"
      },
      {
        "src": "img/iceland-horse-pet.jpg",
        "alt": "Iceland: horse pet"
      },
      {
        "src": "img/iceland-ice-cave-camera.jpg",
        "alt": "Iceland: ice cave camera"
      },
      {
        "src": "img/iceland-ice-cave-silhouette.jpg",
        "alt": "Iceland: ice cave silhouette"
      },
      {
        "src": "img/iceland-ice-cave-touch.jpg",
        "alt": "Iceland: ice cave touch"
      },
      {
        "src": "img/iceland-kirkjufell.jpg",
        "alt": "Iceland: kirkjufell"
      },
      {
        "src": "img/iceland-lava-waves.jpg",
        "alt": "Iceland: lava waves"
      },
      {
        "src": "img/iceland-lone-house.jpg",
        "alt": "Iceland: lone house"
      },
      {
        "src": "img/iceland-modern-building.jpg",
        "alt": "Iceland: modern building"
      },
      {
        "src": "img/iceland-mossy-pinnacle.jpg",
        "alt": "Iceland: mossy pinnacle"
      },
      {
        "src": "img/iceland-mountain-gaze.jpg",
        "alt": "Iceland: mountain gaze"
      },
      {
        "src": "img/iceland-mountain-walk.jpg",
        "alt": "Iceland: mountain walk"
      },
      {
        "src": "img/iceland-night-duo-dance.jpg",
        "alt": "Iceland: night duo dance"
      },
      {
        "src": "img/iceland-night-group.jpg",
        "alt": "Iceland: night group"
      },
      {
        "src": "img/iceland-night-portrait.jpg",
        "alt": "Iceland: night portrait"
      },
      {
        "src": "img/iceland-red-canyon.jpg",
        "alt": "Iceland: red canyon"
      },
      {
        "src": "img/iceland-road-arms-up.jpg",
        "alt": "Iceland: road arms up"
      },
      {
        "src": "img/iceland-road-celebrate.jpg",
        "alt": "Iceland: road celebrate"
      },
      {
        "src": "img/iceland-snow-crouch.jpg",
        "alt": "Iceland: snow crouch"
      },
      {
        "src": "img/iceland-snow-dance.jpg",
        "alt": "Iceland: snow dance"
      },
      {
        "src": "img/iceland-snowfall-arms.jpg",
        "alt": "Iceland: snowfall arms"
      },
      {
        "src": "img/iceland-swing-mountains.jpg",
        "alt": "Iceland: swing mountains"
      },
      {
        "src": "img/iceland-troll-van.jpg",
        "alt": "Iceland: troll van"
      },
      {
        "src": "img/iceland-walk-pink-sky.jpg",
        "alt": "Iceland: walk pink sky"
      },
      {
        "src": "img/iceland-waves-crash.jpg",
        "alt": "Iceland: waves crash"
      },
      {
        "src": "img/iceland-waves-rocks-above.jpg",
        "alt": "Iceland: waves rocks above"
      },
      {
        "src": "img/iceland-whale-card.jpg",
        "alt": "Iceland: whale card"
      }
    ]
  },
  "switzerland": {
    "title": "Switzerland",
    "description": "Travel photographs from Switzerland.",
    "items": [
      {
        "src": "img/switzerland-campervans.jpg",
        "alt": "Switzerland: campervans"
      },
      {
        "src": "img/switzerland-cathedral-aisle.jpg",
        "alt": "Switzerland: cathedral aisle"
      },
      {
        "src": "img/switzerland-cathedral-apse.jpg",
        "alt": "Switzerland: cathedral apse"
      },
      {
        "src": "img/switzerland-cathedral-entrance.jpg",
        "alt": "Switzerland: cathedral entrance"
      },
      {
        "src": "img/switzerland-cathedral-statues.jpg",
        "alt": "Switzerland: cathedral statues"
      },
      {
        "src": "img/switzerland-chalet-aerial.jpg",
        "alt": "Switzerland: chalet aerial"
      },
      {
        "src": "img/switzerland-gondola.jpg",
        "alt": "Switzerland: gondola"
      },
      {
        "src": "img/switzerland-gornergrat-bahn.jpg",
        "alt": "Switzerland: gornergrat bahn"
      },
      {
        "src": "img/switzerland-observatory.jpg",
        "alt": "Switzerland: observatory"
      },
      {
        "src": "img/switzerland-snow-dance.jpg",
        "alt": "Switzerland: snow dance"
      },
      {
        "src": "img/switzerland-snow-joy.jpg",
        "alt": "Switzerland: snow joy"
      },
      {
        "src": "img/switzerland-snow-peak.jpg",
        "alt": "Switzerland: snow peak"
      },
      {
        "src": "img/switzerland-snow-reflection.jpg",
        "alt": "Switzerland: snow reflection"
      },
      {
        "src": "img/switzerland-sticker-pole.jpg",
        "alt": "Switzerland: sticker pole"
      },
      {
        "src": "img/switzerland-swiss-flag.jpg",
        "alt": "Switzerland: swiss flag"
      },
      {
        "src": "img/switzerland-train-window.jpg",
        "alt": "Switzerland: train window"
      },
      {
        "src": "img/switzerland-village-green.jpg",
        "alt": "Switzerland: village green"
      },
      {
        "src": "img/switzerland-zermatt-matterhorn.jpg",
        "alt": "Switzerland: zermatt matterhorn"
      },
      {
        "src": "img/switzerland-zermatt-portrait.jpg",
        "alt": "Switzerland: zermatt portrait"
      }
    ]
  },
  "us": {
    "title": "United States",
    "description": "Travel photographs from the United States.",
    "items": [
      {
        "src": "img/us-abstract-art.jpeg",
        "alt": "United States: abstract art"
      },
      {
        "src": "img/us-beach-crowd.jpeg",
        "alt": "United States: beach crowd"
      },
      {
        "src": "img/us-beach-palm.jpeg",
        "alt": "United States: beach palm"
      },
      {
        "src": "img/us-beach-portrait.jpeg",
        "alt": "United States: beach portrait"
      },
      {
        "src": "img/us-beach-walkers.jpeg",
        "alt": "United States: beach walkers"
      },
      {
        "src": "img/us-bishop-hinge.jpeg",
        "alt": "United States: bishop hinge"
      },
      {
        "src": "img/us-cast-faces.jpeg",
        "alt": "United States: cast faces"
      },
      {
        "src": "img/us-cruise-sunset.jpeg",
        "alt": "United States: cruise sunset"
      },
      {
        "src": "img/us-flags.jpeg",
        "alt": "United States: flags"
      },
      {
        "src": "img/us-honolulu-skyline.jpeg",
        "alt": "United States: honolulu skyline"
      },
      {
        "src": "img/us-lanikai-beach.jpeg",
        "alt": "United States: lanikai beach"
      },
      {
        "src": "img/us-lego-city.jpeg",
        "alt": "United States: lego city"
      },
      {
        "src": "img/us-palms-building.jpeg",
        "alt": "United States: palms building"
      },
      {
        "src": "img/us-palms-convention.jpeg",
        "alt": "United States: palms convention"
      },
      {
        "src": "img/us-palms-rainbow.jpeg",
        "alt": "United States: palms rainbow"
      },
      {
        "src": "img/us-palms-sky.jpeg",
        "alt": "United States: palms sky"
      },
      {
        "src": "img/us-park-walk.jpeg",
        "alt": "United States: park walk"
      },
      {
        "src": "img/us-petroglyph-display.jpeg",
        "alt": "United States: petroglyph display"
      },
      {
        "src": "img/us-poolside-path.jpeg",
        "alt": "United States: poolside path"
      },
      {
        "src": "img/us-vintage-photos.jpeg",
        "alt": "United States: vintage photos"
      }
    ]
  },
  "thailand": {
    "title": "Thailand",
    "description": "Travel photographs from Thailand.",
    "items": [
      {
        "src": "img/thailand-bangkok-street.jpeg",
        "alt": "Thailand: bangkok street"
      },
      {
        "src": "img/thailand-bangkok-traffic.jpeg",
        "alt": "Thailand: bangkok traffic"
      },
      {
        "src": "img/thailand-brahma-head.jpeg",
        "alt": "Thailand: brahma head"
      },
      {
        "src": "img/thailand-bts-station.jpeg",
        "alt": "Thailand: bts station"
      },
      {
        "src": "img/thailand-buddha-back-spire.jpeg",
        "alt": "Thailand: buddha back spire"
      },
      {
        "src": "img/thailand-buddha-canal.jpeg",
        "alt": "Thailand: buddha canal"
      },
      {
        "src": "img/thailand-buddha-statues.jpeg",
        "alt": "Thailand: buddha statues"
      },
      {
        "src": "img/thailand-cafe-above.jpeg",
        "alt": "Thailand: cafe above"
      },
      {
        "src": "img/thailand-cafe-drinks.jpeg",
        "alt": "Thailand: cafe drinks"
      },
      {
        "src": "img/thailand-cafe-thai-wall.jpeg",
        "alt": "Thailand: cafe thai wall"
      },
      {
        "src": "img/thailand-chiang-mai-temple.jpeg",
        "alt": "Thailand: chiang mai temple"
      },
      {
        "src": "img/thailand-giant-buddha-profile.jpeg",
        "alt": "Thailand: giant buddha profile"
      },
      {
        "src": "img/thailand-gold-artifacts.jpeg",
        "alt": "Thailand: gold artifacts"
      },
      {
        "src": "img/thailand-golden-pagoda.jpeg",
        "alt": "Thailand: golden pagoda"
      },
      {
        "src": "img/thailand-grand-palace-roof.jpeg",
        "alt": "Thailand: grand palace roof"
      },
      {
        "src": "img/thailand-hotel-morning.jpeg",
        "alt": "Thailand: hotel morning"
      },
      {
        "src": "img/thailand-iced-drink.jpeg",
        "alt": "Thailand: iced drink"
      },
      {
        "src": "img/thailand-ivory-carvings.jpeg",
        "alt": "Thailand: ivory carvings"
      },
      {
        "src": "img/thailand-khon-collection.jpeg",
        "alt": "Thailand: khon collection"
      },
      {
        "src": "img/thailand-khon-masks.jpeg",
        "alt": "Thailand: khon masks"
      },
      {
        "src": "img/thailand-longtail-dragon.jpeg",
        "alt": "Thailand: longtail dragon"
      },
      {
        "src": "img/thailand-motorbikes.jpeg",
        "alt": "Thailand: motorbikes"
      },
      {
        "src": "img/thailand-national-museum.jpeg",
        "alt": "Thailand: national museum"
      },
      {
        "src": "img/thailand-reclining-buddha.jpeg",
        "alt": "Thailand: reclining buddha"
      },
      {
        "src": "img/thailand-rice-bowl.jpeg",
        "alt": "Thailand: rice bowl"
      },
      {
        "src": "img/thailand-seated-buddha.jpeg",
        "alt": "Thailand: seated buddha"
      },
      {
        "src": "img/thailand-selfie.jpeg",
        "alt": "Thailand: selfie"
      },
      {
        "src": "img/thailand-spires-dusk.jpeg",
        "alt": "Thailand: spires dusk"
      },
      {
        "src": "img/thailand-stone-relief.jpeg",
        "alt": "Thailand: stone relief"
      },
      {
        "src": "img/thailand-street-food.jpeg",
        "alt": "Thailand: street food"
      },
      {
        "src": "img/thailand-street-signs.jpeg",
        "alt": "Thailand: street signs"
      },
      {
        "src": "img/thailand-temple-cat.jpeg",
        "alt": "Thailand: temple cat"
      },
      {
        "src": "img/thailand-temple-ceiling.jpeg",
        "alt": "Thailand: temple ceiling"
      },
      {
        "src": "img/thailand-temple-monk.jpeg",
        "alt": "Thailand: temple monk"
      }
    ]
  },
  "nepal": {
    "title": "Nepal",
    "description": "Travel photographs from Nepal.",
    "items": [
      {
        "src": "img/nepal-abc-bridge-crossing-mountains.jpg",
        "alt": "Nepal: ABC bridge crossing mountains"
      },
      {
        "src": "img/nepal-abc-forest-roots-trek.jpg",
        "alt": "Nepal: ABC forest roots trek"
      },
      {
        "src": "img/nepal-abc-river-bridge-cliff.jpg",
        "alt": "Nepal: ABC river bridge cliff"
      },
      {
        "src": "img/nepal-abc-silhouette-doorway.jpg",
        "alt": "Nepal: ABC silhouette doorway"
      },
      {
        "src": "img/nepal-abc-snow-valley-wide.jpg",
        "alt": "Nepal: ABC snow valley wide"
      },
      {
        "src": "img/nepal-breakfast-croissant.jpg",
        "alt": "Nepal: breakfast croissant"
      },
      {
        "src": "img/nepal-bus-dashboard-interior.jpg",
        "alt": "Nepal: bus dashboard interior"
      },
      {
        "src": "img/nepal-cafe-dog-sleeping.jpg",
        "alt": "Nepal: cafe dog sleeping"
      },
      {
        "src": "img/nepal-cafe-guestbook-notes.jpg",
        "alt": "Nepal: cafe guestbook notes"
      },
      {
        "src": "img/nepal-dog-balcony-mountains.jpg",
        "alt": "Nepal: dog balcony mountains"
      },
      {
        "src": "img/nepal-dog-photo-wall.jpg",
        "alt": "Nepal: dog photo wall"
      },
      {
        "src": "img/nepal-dog-portrait-balcony.jpg",
        "alt": "Nepal: dog portrait balcony"
      },
      {
        "src": "img/nepal-himalaya-guesthouse-sign.jpg",
        "alt": "Nepal: himalaya guesthouse sign"
      },
      {
        "src": "img/nepal-jeep-mountain-road.jpg",
        "alt": "Nepal: jeep mountain road"
      },
      {
        "src": "img/nepal-lodge-breakfast-coffee.jpg",
        "alt": "Nepal: lodge breakfast coffee"
      },
      {
        "src": "img/nepal-pashupatinath-overlook-bw.jpg",
        "alt": "Nepal: pashupatinath overlook BW"
      },
      {
        "src": "img/nepal-pashupatinath-temple-night.jpg",
        "alt": "Nepal: pashupatinath temple night"
      },
      {
        "src": "img/nepal-pokhara-blue-bus.jpg",
        "alt": "Nepal: pokhara blue bus"
      },
      {
        "src": "img/nepal-pokhara-street-smoke.jpg",
        "alt": "Nepal: pokhara street smoke"
      },
      {
        "src": "img/nepal-prayer-flags-valley.jpg",
        "alt": "Nepal: prayer flags valley"
      },
      {
        "src": "img/nepal-rest-stone-house.jpg",
        "alt": "Nepal: rest stone house"
      },
      {
        "src": "img/nepal-trail-mule-caravan.jpg",
        "alt": "Nepal: trail mule caravan"
      },
      {
        "src": "img/nepal-tree-silhouette-blue-mountain.jpg",
        "alt": "Nepal: tree silhouette blue mountain"
      },
      {
        "src": "img/nepal-trek-dirt-road-sky.jpg",
        "alt": "Nepal: trek dirt road sky"
      },
      {
        "src": "img/nepal-village-shop-ayurvedic.jpg",
        "alt": "Nepal: village shop ayurvedic"
      }
    ]
  },
  "egypt": {
    "title": "Egypt",
    "description": "Travel photographs from Egypt.",
    "items": [
      {
        "src": "img/egypt-amphitheater-statue.jpg",
        "alt": "Egypt: amphitheater statue"
      },
      {
        "src": "img/egypt-amphitheater-steps.jpg",
        "alt": "Egypt: amphitheater steps"
      },
      {
        "src": "img/egypt-ancient-painting.jpg",
        "alt": "Egypt: ancient painting"
      },
      {
        "src": "img/egypt-camel-caravan.jpg",
        "alt": "Egypt: camel caravan"
      },
      {
        "src": "img/egypt-camel-ride-desert.jpg",
        "alt": "Egypt: camel ride desert"
      },
      {
        "src": "img/egypt-cave-church-arms.jpg",
        "alt": "Egypt: cave church arms"
      },
      {
        "src": "img/egypt-cave-church-interior.jpg",
        "alt": "Egypt: cave church interior"
      },
      {
        "src": "img/egypt-cave-church-selfie.jpg",
        "alt": "Egypt: cave church selfie"
      },
      {
        "src": "img/egypt-cliff-arms-raised.jpg",
        "alt": "Egypt: cliff arms raised"
      },
      {
        "src": "img/egypt-cliff-edge-sit.jpg",
        "alt": "Egypt: cliff edge sit"
      },
      {
        "src": "img/egypt-cliff-ocean-sit.jpg",
        "alt": "Egypt: cliff ocean sit"
      },
      {
        "src": "img/egypt-cliff-ocean-wide.jpg",
        "alt": "Egypt: cliff ocean wide"
      },
      {
        "src": "img/egypt-cliff-top-perch.jpg",
        "alt": "Egypt: cliff top perch"
      },
      {
        "src": "img/egypt-mosque-chandeliers.jpg",
        "alt": "Egypt: mosque chandeliers"
      },
      {
        "src": "img/egypt-museum-artifacts.jpg",
        "alt": "Egypt: museum artifacts"
      },
      {
        "src": "img/egypt-museum-busts.jpg",
        "alt": "Egypt: museum busts"
      },
      {
        "src": "img/egypt-museum-fresco.jpg",
        "alt": "Egypt: museum fresco"
      },
      {
        "src": "img/egypt-museum-hall.jpg",
        "alt": "Egypt: museum hall"
      },
      {
        "src": "img/egypt-museum-sarcophagus.jpg",
        "alt": "Egypt: museum sarcophagus"
      },
      {
        "src": "img/egypt-pyramid-palms.jpg",
        "alt": "Egypt: pyramid palms"
      },
      {
        "src": "img/egypt-pyramids.jpg",
        "alt": "Egypt: pyramids"
      },
      {
        "src": "img/egypt-rock-arch.jpg",
        "alt": "Egypt: rock arch"
      },
      {
        "src": "img/egypt-rocks-ocean-closeup.jpg",
        "alt": "Egypt: rocks ocean closeup"
      },
      {
        "src": "img/egypt-sand-bay-backpack.jpg",
        "alt": "Egypt: sand bay backpack"
      },
      {
        "src": "img/egypt-sand-beach-gaze.jpg",
        "alt": "Egypt: sand beach gaze"
      }
    ]
  },
  "indonesia": {
    "title": "Indonesia",
    "description": "Travel photographs from Indonesia.",
    "items": [
      {
        "src": "img/indonesia-bali-jungle-palms.jpg",
        "alt": "Indonesia: bali jungle palms"
      },
      {
        "src": "img/indonesia-bali-palm-sunset.jpg",
        "alt": "Indonesia: bali palm sunset"
      },
      {
        "src": "img/indonesia-bali-temple-ceremony.jpg",
        "alt": "Indonesia: bali temple ceremony"
      },
      {
        "src": "img/indonesia-bali-temple-gate-night.jpg",
        "alt": "Indonesia: bali temple gate night"
      },
      {
        "src": "img/indonesia-bali-warrior-sculpture.jpg",
        "alt": "Indonesia: bali warrior sculpture"
      },
      {
        "src": "img/indonesia-beach-gear-sand.jpg",
        "alt": "Indonesia: beach gear sand"
      },
      {
        "src": "img/indonesia-bromo-crater-dance.jpg",
        "alt": "Indonesia: bromo crater dance"
      },
      {
        "src": "img/indonesia-bromo-crater-interior.jpg",
        "alt": "Indonesia: bromo crater interior"
      },
      {
        "src": "img/indonesia-bromo-crater-sign.jpg",
        "alt": "Indonesia: bromo crater sign"
      },
      {
        "src": "img/indonesia-bromo-crater-sit.jpg",
        "alt": "Indonesia: bromo crater sit"
      },
      {
        "src": "img/indonesia-bromo-crater-smoke.jpg",
        "alt": "Indonesia: bromo crater smoke"
      },
      {
        "src": "img/indonesia-bromo-dawn-portrait.jpg",
        "alt": "Indonesia: bromo dawn portrait"
      },
      {
        "src": "img/indonesia-bromo-foggy-walk.jpg",
        "alt": "Indonesia: bromo foggy walk"
      },
      {
        "src": "img/indonesia-bromo-silhouette-dawn.jpg",
        "alt": "Indonesia: bromo silhouette dawn"
      },
      {
        "src": "img/indonesia-bromo-street-motorcycle.jpg",
        "alt": "Indonesia: bromo street motorcycle"
      },
      {
        "src": "img/indonesia-bromo-tree-frame-clouds.jpg",
        "alt": "Indonesia: bromo tree frame clouds"
      },
      {
        "src": "img/indonesia-bromo-volcano-wide.jpg",
        "alt": "Indonesia: bromo volcano wide"
      },
      {
        "src": "img/indonesia-nusa-penida-aerial-cove.jpg",
        "alt": "Indonesia: nusa penida aerial cove"
      },
      {
        "src": "img/indonesia-nusa-penida-aerial-foliage.jpg",
        "alt": "Indonesia: nusa penida aerial foliage"
      },
      {
        "src": "img/indonesia-nusa-penida-aerial-shore.jpg",
        "alt": "Indonesia: nusa penida aerial shore"
      },
      {
        "src": "img/indonesia-nusa-penida-beach-action.jpg",
        "alt": "Indonesia: nusa penida beach action"
      },
      {
        "src": "img/indonesia-nusa-penida-beach-dance.jpg",
        "alt": "Indonesia: nusa penida beach dance"
      },
      {
        "src": "img/indonesia-nusa-penida-beach-gaze-ocean.jpg",
        "alt": "Indonesia: nusa penida beach gaze ocean"
      },
      {
        "src": "img/indonesia-nusa-penida-beach-wide.jpg",
        "alt": "Indonesia: nusa penida beach wide"
      },
      {
        "src": "img/indonesia-nusa-penida-sea-cliffs.jpg",
        "alt": "Indonesia: nusa penida sea cliffs"
      },
      {
        "src": "img/indonesia-nusa-penida-wave-crash.jpg",
        "alt": "Indonesia: nusa penida wave crash"
      },
      {
        "src": "img/indonesia-tumpak-sewu-waterfall-arms.jpg",
        "alt": "Indonesia: tumpak sewu waterfall arms"
      },
      {
        "src": "img/indonesia-tumpak-sewu-waterfall-selfie.jpg",
        "alt": "Indonesia: tumpak sewu waterfall selfie"
      }
    ]
  },
  "malaysia": {
    "title": "Malaysia",
    "description": "Travel photographs from Malaysia.",
    "items": [
      {
        "src": "img/malaysia-batu-caves-stairs.jpg",
        "alt": "Malaysia: batu caves stairs"
      },
      {
        "src": "img/malaysia-batu-caves-temple.jpg",
        "alt": "Malaysia: batu caves temple"
      },
      {
        "src": "img/malaysia-kl-skyline-night.jpg",
        "alt": "Malaysia: KL skyline night"
      },
      {
        "src": "img/malaysia-petronas-selfie.jpg",
        "alt": "Malaysia: petronas selfie"
      },
      {
        "src": "img/malaysia-petronas-towers-night.jpg",
        "alt": "Malaysia: petronas towers night"
      },
      {
        "src": "img/malaysia-petronas-towers-portrait.jpg",
        "alt": "Malaysia: petronas towers portrait"
      },
      {
        "src": "img/malaysia-street-food-market.jpg",
        "alt": "Malaysia: street food market"
      }
    ]
  },
  "china": {
    "title": "China",
    "description": "Travel photographs from China.",
    "items": [
      {
        "src": "img/china-backpacker-campus.jpg",
        "alt": "China: backpacker campus"
      },
      {
        "src": "img/china-bronze-vessel-rubbing.jpg",
        "alt": "China: bronze vessel rubbing"
      },
      {
        "src": "img/china-buddha-stone-carving.jpg",
        "alt": "China: buddha stone carving"
      },
      {
        "src": "img/china-calligraphy-scroll.jpg",
        "alt": "China: calligraphy scroll"
      },
      {
        "src": "img/china-coffee-roasters.jpg",
        "alt": "China: coffee roasters"
      },
      {
        "src": "img/china-dagu-glacier-signpost.jpg",
        "alt": "China: dagu glacier signpost"
      },
      {
        "src": "img/china-glacier-boardwalk-portrait.jpg",
        "alt": "China: glacier boardwalk portrait"
      },
      {
        "src": "img/china-glacier-turquoise-lake.jpg",
        "alt": "China: glacier turquoise lake"
      },
      {
        "src": "img/china-metro-red-suitcase.jpg",
        "alt": "China: metro red suitcase"
      },
      {
        "src": "img/china-mountain-hiking-selfie.jpg",
        "alt": "China: mountain hiking selfie"
      },
      {
        "src": "img/china-museum-bodhisattva.jpg",
        "alt": "China: museum bodhisattva"
      },
      {
        "src": "img/china-museum-ceramic-wall.jpg",
        "alt": "China: museum ceramic wall"
      },
      {
        "src": "img/china-museum-mountain-mural.jpg",
        "alt": "China: museum mountain mural"
      },
      {
        "src": "img/china-museum-wood-buddha.jpg",
        "alt": "China: museum wood buddha"
      },
      {
        "src": "img/china-pagoda-golden-spire.jpg",
        "alt": "China: pagoda golden spire"
      },
      {
        "src": "img/china-photo-studio-lights.jpg",
        "alt": "China: photo studio lights"
      },
      {
        "src": "img/china-reed-photographer.jpg",
        "alt": "China: reed photographer"
      },
      {
        "src": "img/china-river-worker-boat.jpg",
        "alt": "China: river worker boat"
      },
      {
        "src": "img/china-sichuan-lake-portrait.jpg",
        "alt": "China: sichuan lake portrait"
      },
      {
        "src": "img/china-snow-mountain-peak.jpg",
        "alt": "China: snow mountain peak"
      },
      {
        "src": "img/china-snow-portrait-bw.jpg",
        "alt": "China: snow portrait BW"
      },
      {
        "src": "img/china-snowboard-gear-bw.jpg",
        "alt": "China: snowboard gear BW"
      },
      {
        "src": "img/china-tang-figurines.jpg",
        "alt": "China: tang figurines"
      },
      {
        "src": "img/china-tea-village-cablecar.jpg",
        "alt": "China: tea village cablecar"
      },
      {
        "src": "img/china-temple-yellow-wall.jpg",
        "alt": "China: temple yellow wall"
      },
      {
        "src": "img/china-tibet-ancient-stupas-valley.jpg",
        "alt": "China: tibet ancient stupas valley"
      },
      {
        "src": "img/china-tibet-highland-road.jpg",
        "alt": "China: tibet highland road"
      },
      {
        "src": "img/china-tibet-plateau-portrait.jpg",
        "alt": "China: tibet plateau portrait"
      },
      {
        "src": "img/china-tibet-prayer-flags-mountains.jpg",
        "alt": "China: tibet prayer flags mountains"
      },
      {
        "src": "img/china-tibet-prayer-flags-peak.jpg",
        "alt": "China: tibet prayer flags peak"
      },
      {
        "src": "img/china-tibet-red-jacket-mountain.jpg",
        "alt": "China: tibet red jacket mountain"
      },
      {
        "src": "img/china-traditional-barbershop.jpg",
        "alt": "China: traditional barbershop"
      },
      {
        "src": "img/china-tsingtao-vintage-poster.jpg",
        "alt": "China: tsingtao vintage poster"
      }
    ]
  },
  "vietnam": {
    "title": "Vietnam",
    "description": "Travel photographs from Vietnam.",
    "items": [
      {
        "src": "img/vietnam-beach-dusk.jpeg",
        "alt": "Vietnam: beach dusk"
      },
      {
        "src": "img/vietnam-bronze-tara.jpeg",
        "alt": "Vietnam: bronze tara"
      },
      {
        "src": "img/vietnam-cham-statue-2.jpeg",
        "alt": "Vietnam: cham statue 2"
      },
      {
        "src": "img/vietnam-cham-statue.jpeg",
        "alt": "Vietnam: cham statue"
      },
      {
        "src": "img/vietnam-corridor.jpeg",
        "alt": "Vietnam: corridor"
      },
      {
        "src": "img/vietnam-hoian-pond-gate.jpeg",
        "alt": "Vietnam: hoian pond gate"
      },
      {
        "src": "img/vietnam-hue-gate-detail.jpeg",
        "alt": "Vietnam: hue gate detail"
      },
      {
        "src": "img/vietnam-hue-imperial-city.jpeg",
        "alt": "Vietnam: hue imperial city"
      },
      {
        "src": "img/vietnam-hue-newspaper.jpeg",
        "alt": "Vietnam: hue newspaper"
      },
      {
        "src": "img/vietnam-hue-ngo-mon.jpeg",
        "alt": "Vietnam: hue NGO MON"
      },
      {
        "src": "img/vietnam-interior.jpeg",
        "alt": "Vietnam: interior"
      },
      {
        "src": "img/vietnam-marble-mountains.jpeg",
        "alt": "Vietnam: marble mountains"
      },
      {
        "src": "img/vietnam-pavilion-archway.jpeg",
        "alt": "Vietnam: pavilion archway"
      },
      {
        "src": "img/vietnam-poolside.jpeg",
        "alt": "Vietnam: poolside"
      },
      {
        "src": "img/vietnam-restaurant.jpeg",
        "alt": "Vietnam: restaurant"
      },
      {
        "src": "img/vietnam-train.jpeg",
        "alt": "Vietnam: train"
      }
    ]
  },
  "korea": {
    "title": "South Korea",
    "description": "Travel photographs from South Korea.",
    "items": [
      {
        "src": "img/korea-bronze-vessel.jpeg",
        "alt": "South Korea: bronze vessel"
      },
      {
        "src": "img/korea-dark-gallery-books.jpeg",
        "alt": "South Korea: dark gallery books"
      },
      {
        "src": "img/korea-gold-crown.jpeg",
        "alt": "South Korea: gold crown"
      },
      {
        "src": "img/korea-hanbok-performance.jpeg",
        "alt": "South Korea: hanbok performance"
      },
      {
        "src": "img/korea-human-skulls.jpeg",
        "alt": "South Korea: human skulls"
      },
      {
        "src": "img/korea-portrait-scroll.jpeg",
        "alt": "South Korea: portrait scroll"
      },
      {
        "src": "img/korea-seated-buddha.jpeg",
        "alt": "South Korea: seated buddha"
      },
      {
        "src": "img/korea-theatre-control-booth.jpeg",
        "alt": "South Korea: theatre control booth"
      }
    ]
  },
  "qatar": {
    "title": "Qatar",
    "description": "Travel photographs from Doha and Lusail, Qatar.",
    "items": [
      {
        "src": "img/qatar-national-museum-passage.jpg",
        "alt": "Passage through the desert-rose forms of the National Museum of Qatar."
      },
      {
        "src": "img/qatar-katara-shade-sails.jpg",
        "alt": "Shade sails above a passage in Katara Cultural Village."
      },
      {
        "src": "img/qatar-museum-of-islamic-art.jpg",
        "alt": "Museum of Islamic Art on the Doha waterfront."
      },
      {
        "src": "img/qatar-national-museum-curves.jpg",
        "alt": "Overlapping architectural curves at the National Museum of Qatar."
      },
      {
        "src": "img/qatar-place-vendome-hands.jpg",
        "alt": "Hands sculpture at Place Vendome in Lusail."
      },
      {
        "src": "img/qatar-pastel-street-stop.jpg",
        "alt": "Pastel buildings and a stop sign in Qatar."
      },
      {
        "src": "img/qatar-national-museum-facade-wide.jpg",
        "alt": "Wide view of the National Museum of Qatar facade."
      },
      {
        "src": "img/qatar-katara-door-06.jpg",
        "alt": "Numbered wooden door in Katara Cultural Village."
      },
      {
        "src": "img/qatar-geometric-skylight.jpg",
        "alt": "Geometric skylight casting patterned light."
      },
      {
        "src": "img/qatar-palms-through-museum.jpg",
        "alt": "Palm trees framed by the National Museum of Qatar."
      },
      {
        "src": "img/qatar-katara-sails-lane.jpg",
        "alt": "Sail-covered lane in Katara Cultural Village."
      },
      {
        "src": "img/qatar-national-museum-sculpture.jpg",
        "alt": "Outdoor sculpture at the National Museum of Qatar."
      },
      {
        "src": "img/qatar-pink-buildings-wide.jpg",
        "alt": "Wide view of pink buildings in Qatar."
      },
      {
        "src": "img/qatar-pink-courtyard-plants.jpg",
        "alt": "Hanging plants in a pink courtyard."
      },
      {
        "src": "img/qatar-national-museum-city-frame.jpg",
        "alt": "Doha buildings framed by the National Museum of Qatar."
      },
      {
        "src": "img/qatar-blue-pots-calligraphy.jpg",
        "alt": "Blue pots beside an Arabic calligraphy wall."
      },
      {
        "src": "img/qatar-pink-door.jpg",
        "alt": "Wooden door set in a pink wall."
      },
      {
        "src": "img/qatar-stained-glass-hall.jpg",
        "alt": "Colourful stained-glass hall in Qatar."
      },
      {
        "src": "img/qatar-courtyard-arches.jpg",
        "alt": "Repeated arches around a quiet courtyard."
      },
      {
        "src": "img/qatar-katara-lantern-wall.jpg",
        "alt": "Lanterns mounted on a wall in Katara Cultural Village."
      },
      {
        "src": "img/qatar-black-door-13.jpg",
        "alt": "Black numbered door in Qatar."
      },
      {
        "src": "img/qatar-palm-walls.jpg",
        "alt": "Palm tree between pale architectural walls."
      },
      {
        "src": "img/qatar-katara-horse-mural.jpg",
        "alt": "Horse mural in Katara Cultural Village."
      },
      {
        "src": "img/qatar-bougainvillea-window.jpg",
        "alt": "Bougainvillea beside a shaded window."
      },
      {
        "src": "img/qatar-evening-building-frame.jpg",
        "alt": "Evening building framed by shade cloth."
      },
      {
        "src": "img/qatar-red-bougainvillea-arch.jpg",
        "alt": "Red bougainvillea beside an archway."
      },
      {
        "src": "img/qatar-national-museum-wide.jpg",
        "alt": "Desert-rose architecture of the National Museum of Qatar."
      }
    ]
  },
  "czech": {
    "title": "Czech Republic",
    "description": "Travel photographs from Prague, Czech Republic.",
    "items": [
      {
        "src": "img/czech-08-red-walled-passage.jpg",
        "alt": "A silhouetted person crossing a red-walled passage."
      },
      {
        "src": "img/czech-04-dark-restaurant-window.jpg",
        "alt": "Empty restaurant tables beside a bright window in a dark interior."
      },
      {
        "src": "img/czech-05-red-white-tram.jpg",
        "alt": "Red-and-white city tram beneath a blue, cloud-filled sky."
      },
      {
        "src": "img/czech-07-passengers-through-tram-window.jpg",
        "alt": "Passengers seen through the window of a red-and-white tram."
      },
      {
        "src": "img/czech-03-cobbled-street-cafe.jpg",
        "alt": "People seated at outdoor cafe tables on a cobbled street."
      },
      {
        "src": "img/czech-24-window-framed-architecture.jpg",
        "alt": "Sunlit stone architecture framed by dark window mullions."
      },
      {
        "src": "img/czech-11-sculpture-stained-glass.jpg",
        "alt": "Stone sculpture beside a stained-glass window inside a cathedral."
      },
      {
        "src": "img/czech-14-statue-stained-glass.jpg",
        "alt": "A dark religious statue silhouetted against stained glass."
      },
      {
        "src": "img/czech-16-statue-gilded-screen.jpg",
        "alt": "Stone statue and gilded screen lit by sunlight inside a cathedral."
      },
      {
        "src": "img/czech-17-bronze-figure-stained-glass.jpg",
        "alt": "Bronze praying figure beside tall stained-glass windows."
      },
      {
        "src": "img/czech-18-stained-glass-from-below.jpg",
        "alt": "Stained-glass windows and Gothic stonework seen from below."
      },
      {
        "src": "img/czech-10-visitors-cathedral-nave.jpg",
        "alt": "Visitors standing in a dim cathedral nave beside tall windows."
      },
      {
        "src": "img/czech-21-organ-pipes-circular-window.jpg",
        "alt": "Silver organ pipes framed by a circular stained-glass window."
      },
      {
        "src": "img/czech-15-blue-gold-religious-mural.jpg",
        "alt": "Blue-and-gold religious mural depicting a crowned figure."
      },
      {
        "src": "img/czech-09-gothic-cathedral-exterior.jpg",
        "alt": "Gothic cathedral exterior under a deep blue sky."
      },
      {
        "src": "img/czech-25-church-courtyard.jpg",
        "alt": "Historic church buildings around a crowded sunlit courtyard."
      },
      {
        "src": "img/czech-28-crowded-pastel-street.jpg",
        "alt": "Crowds walking along a narrow street between pastel buildings."
      },
      {
        "src": "img/czech-30-red-tiled-rooftops.jpg",
        "alt": "Red tiled rooftops across the historic city center."
      },
      {
        "src": "img/czech-32-prague-skyline-bridge.jpg",
        "alt": "Prague skyline and bridge seen across red rooftops and trees."
      },
      {
        "src": "img/czech-01-prague-castle-riverside.jpg",
        "alt": "Prague Castle and riverside buildings under a cloudy sky."
      },
      {
        "src": "img/czech-02-historic-street-tram-wires.jpg",
        "alt": "Sunlit street lined with historic buildings and tram wires."
      },
      {
        "src": "img/czech-29-quiet-cobbled-courtyard.jpg",
        "alt": "Parked cars in a quiet cobbled courtyard between pale buildings."
      },
      {
        "src": "img/czech-06-passengers-inside-tram.jpg",
        "alt": "Passengers seated inside a city tram beside sunlit doors."
      },
      {
        "src": "img/czech-12-gothic-windows-interior.jpg",
        "alt": "Gothic windows and carved details in a dim cathedral interior."
      },
      {
        "src": "img/czech-13-angels-gilded-crest.jpg",
        "alt": "Sculpted angels gathered around a gilded crest inside a cathedral."
      },
      {
        "src": "img/czech-19-large-stained-glass-window.jpg",
        "alt": "Large stained-glass window framed by Gothic stone arches."
      },
      {
        "src": "img/czech-20-organ-circular-window.jpg",
        "alt": "Cathedral organ beneath a circular stained-glass window."
      },
      {
        "src": "img/czech-22-windows-scaffolding.jpg",
        "alt": "Tall stained-glass windows and scaffolding inside a cathedral."
      },
      {
        "src": "img/czech-23-shadowed-gothic-arches.jpg",
        "alt": "Shadowed Gothic arches and windows inside a cathedral."
      },
      {
        "src": "img/czech-26-diners-sunlit-courtyard.jpg",
        "alt": "Diners in a sunlit courtyard outside a restaurant."
      },
      {
        "src": "img/czech-27-cafe-fountain.jpg",
        "alt": "Outdoor cafe tables around a small circular fountain."
      },
      {
        "src": "img/czech-31-rooftops-church-towers.jpg",
        "alt": "Historic rooftops and church towers beside a green hillside."
      }
    ]
  }
};
